config/routes.rb
Whiteboard::Application.routes.draw do

	devise_for :students
	devise_for :teachers
	
	resources :students, only: [:show]

	resources :teachers, only: [:show]

	resources :courses do
		resources :assignments
		resources :grades
		resources :topics

		resources :events, except: [:index]
		get '/calendar' => 'events#index'

		resources :enrolls, only: [:create, :index, :destroy]
	end

	root to: 'pages#home'
end

app/models/grade.rb
# == Schema Information
#
# Table name: grades
#
#  id            :integer          not null, primary key
#  student_id    :integer
#  assignment_id :integer
#  points        :integer
#  created_at    :datetime
#  updated_at    :datetime
#

class Grade < ActiveRecord::Base

	# Callbacks

	# Validations

	# Relationships
	belongs_to :assignment
	belongs_to :student

	# Functions
	def percentage
		(points.to_f / assignment.points.to_f * 100).to_i
	end
end

app/controllers/grades_controller.rb
class GradesController < ApplicationController

	before_filter :authenticate_teacher!
	before_filter :find_course
	before_filter :find_grade, except: [:new, :create, :index]

	def new
		@grade = Grade.new
	end

	def create
		@grade = Grade.new(grade_params)

		if @grade.save
			flash[:success] = "Grade was created"
			redirect_to course_grade_path(@course, @grade)
		else
			flash[:error] = "Error while creating grade"
			render "new"
		end
	end

	def show
	end

	def edit
	end

	def update
		if @grade.update_attributes(grade_params)
			flash[:success] = "Grade was updated"
			redirect_to course_grade_path(@course, @grade)
		else
			flash[:error] = "Error while updating grade"
			render "edit"
		end
	end

	def index
		@assignments = @course.assignments
		@grades = Grade.all

		@sorting = params[:sort]
	end

	def destroy
		@grade.destroy!

		flash[:info] = "Grade was deleted"
		redirect_to grades_path
	end

	private
		def grade_params
			params.require(:grade).permit(:student_id, :assignment_id, :points)
		end

		def find_course
			@course = Course.find(params[:course_id])
		end

		def find_grade
			@grade = Grade.find(params[:id])
		end
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/views/grades/edit.html.erb
<div class="container">
	<div class="panel panel-info">
		<div class="panel-heading">
			<strong>Edit Grade</strong>
		</div>

		<div class="panel-body">
			<%= form_for [@course, @grade] do |f| %>

				<div>
					<%= f.label :assignment_id, "Assignment" %>
					<%= f.select :assignment_id, options_for_select(assignment_list), {}, :class => "form-control" %>
				</div>

				<div class="input-div">
					<%= f.label :student_id, "Student" %>
					<%= f.select :student_id, options_for_select(student_list), {}, :class => "form-control" %>
				</div>

				<div class="input-div">
					<%= f.label :points %>
					<%= f.text_field :points, :class => "form-control " %>
				</div>

				<div class="input-div">
					<%= f.submit "Edit", :class => "btn btn-default" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/grades/index.html.erb
<div class="container">
	<h1><%= course_id(@course) %> Grades</h1>

	<p>Sorting</p>
	<p><%= link_to "Assignment", course_grades_path(@course, sort: "assignment") %> | <%= link_to "Student", course_grades_path(@course, sort: "student") %> | <%= link_to "None", course_grades_path(@course, sort: "none") %></p>

	<% if @sorting == "student" %>

		<% @course.students.each do |student| %>
			<h3><%= student.name %></h3>
			<table class="table table-striped table-hover">
				<thead>
					<td>Assignment</td>
					<td>Points</td>
					<td>Max</td>
					<td>Percentage</td>
				</thead>

				<tbody>
					<% titles = Array.new %>
					<% student.grades.each do |grade| %>
						<% titles << grade.assignment.title %>
						<tr>
							<td><%= link_to grade.assignment.title %></td>
							<td><%= grade.points %></td>
							<td><%= grade.assignment.points %></td>
							<td><%= "#{grade.percentage}%" %></td>
						</tr>
					<% end %>
					<tr>
						<td>Total</td>
						<td><%= sp = student.grades.sum(:points).to_f %></td>
						<td><%= ap = @assignments.where(title: titles).sum(:points) %></td>
						<td><%= "#{sp / ap * 100.0}%" %></td>
					</tr>
				</tbody>
			</table>
		<% end %>

	<% elsif @sorting == "none" %>

		<h3>All Grades</h3>
		<table class="table table-striped table-hover">
			<thead>
				<td>Assignment</td>
				<td>Student</td>
				<td>Points</td>
				<td>Max</td>
				<td>Percentage</td>
			</thead>

			<tbody>
				<% @grades.each do |grade| %>
					<tr>
						<td><%= grade.assignment.title %>
						<td><%= link_to grade.student.name, student_path(grade.student) %></td>
						<td><%= grade.points %></td>
						<td><%= grade.assignment.points %></td>
						<td><%= "#{grade.percentage}%" %></td>
					</tr>
				<% end %>
			</tbody>
		</table>

	<% else %>

		<% @assignments.each do |assignment| %>
			<h3><%= assignment.title %></h3>
			<table class="table table-striped table-hover">
				<thead>
					<td>Student</td>
					<td>Points</td>
					<td>Max</td>
					<td>Percentage</td>
				</thead>

				<tbody>
					<% assignment.grades.each do |grade| %>
						<tr>
							<td><%= link_to grade.student.name, student_path(grade.student) %></td>
							<td><%= grade.points %></td>
							<td><%= assignment.points %></td>
							<td><%= "#{grade.percentage}%" %></td>
						</tr>
					<% end %>
					<tr>
						<td>Average</td>
						<td colspan="2"><%= assignment.grades.average(:points).to_f %></td>
						<td><%= "#{assignment.grades.to_a.sum(&:percentage).to_f / assignment.grades.to_a.size}%" %></td>
					</tr>
				</tbody>
			</table>
		<% end %>
	<% end %>

	<p><%= link_to "New", new_course_grade_path(@course) %></p>
</div>

app/views/grades/new.html.erb
<div class="container">
	<div class="panel panel-info">
		<div class="panel-heading">
			<strong>Enter Grade</strong>
		</div>

		<div class="panel-body">
			<%= form_for [@course, @grade] do |f| %>

				<div>
					<%= f.label :assignment_id, "Assignment" %>
					<%= f.select :assignment_id, options_for_select(assignment_list(@course)), {}, :class => "form-control" %>
				</div>

				<div class="input-div">
					<%= f.label :student_id, "Student" %>
					<%= f.select :student_id, options_for_select(student_list(@course)), {}, :class => "form-control" %>
				</div>

				<div class="input-div">
					<%= f.label :points %>
					<%= f.text_field :points, :class => "form-control " %>
				</div>

				<div class="input-div">
					<%= f.submit "Submit", :class => "btn btn-default" %>
				</div>
			<% end %>
		</div>
	</div>
</div>