config/routes.rb
Whiteboard::Application.routes.draw do

	devise_for :students
	devise_for :teachers
	
	resources :students, only: [:show]

	resources :teachers, only: [:show]

	resources :courses do
		resources :assignments
		resources :grades
		resources :topics

		resources :events, except: [:index]
		get '/calendar' => 'events#index'

		resources :enrolls, only: [:create, :index, :destroy]
	end

	root to: 'pages#home'
end

app/models/topic.rb
# == Schema Information
#
# Table name: topics
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  course_id  :integer
#  title      :string(255)
#  body       :text
#  created_at :datetime
#  updated_at :datetime
#

class Topic < ActiveRecord::Base

	# Callbacks

	# Validations

	# Relationships
	belongs_to :course
	belongs_to :user

	# Functions

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

	before_filter :find_course
	before_filter :find_topic, except: [:new, :create, :index]
	before_filter :authenticate_teacher!

	def new
		@topic = Topic.new
	end

	def create
		@topic = @course.topics.build(topic_params)

		if @topic.save
			flash[:success] = "Topic was created"
			redirect_to course_topic_path(@course, @topic)
		else
			flash[:error] = "Error while creating topic"
			render "new"
		end
	end

	def show
	end

	def edit
	end

	def update
		if @topic.update_attributes(topic_params)
			flash[:success] = "Topic was updated"
			redirect_to course_topic_path(@course, @topic)
		else
			flash[:error] = "Error while updating topic"
			render "edit"
		end
	end

	def index
		@topics = @course.topics
	end

	def destroy
		@topic.destroy!

		flash[:info] = "Topic was deleted"
		redirect_to course_topics_path(@course)
	end

	private
		def topic_params
			params.require(:topic).permit(:title, :user_id, :body)
		end

		def find_course
			@course = Course.find(params[:course_id])
		end

		def find_topic
			@topic = Topic.find(params[:id])
		end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/edit.html.erb
<div class="container">
	<div class="panel panel-info">
		<div class="panel-heading">
			<strong>Edit Topic</strong>
		</div>

		<div class="panel-body">
			<%= form_for [@course, @topic] do |f| %>
				<div>
					<%= f.label :title %>
					<%= f.text_field :title, :autofocus => true, :class => "form-control" %>
				</div>

				<div class="input-div">
					<%= f.label :body %>
					<%= f.text_area :body, :class => "form-control" %>
				</div>

				<div class="input-div">
					<%= f.submit "Update", :class => "btn btn-default" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/topics/index.html.erb
<div class="container">
	<h1>Topics</h1>
	<table class="table table-striped table-hover">
		<thead>
			<td>Title</td>
			<td>Posted At</td>
		</thead>

		<tbody>
			<% @topics.each do |topic| %>
				<tr>
					<td><%= link_to topic.title, course_topic_path(@course, topic) %></td>
					<td><%= time_tag topic.created_at.localtime %></td>
				</tr>
			<% end %>
		</tbody>
	</table>

	<p><%= link_to "New", new_course_topic_path(@course) %></p>
</div>

app/views/topics/new.html.erb
<div class="container">
	<div class="panel panel-info">
		<div class="panel-heading">
			<strong>Create Topic</strong>
		</div>

		<div class="panel-body">
			<%= form_for [@course, @topic] do |f| %>
				<%= f.hidden_field :user_id, value: current_teacher.id %>

				<div>
					<%= f.label :title %>
					<%= f.text_field :title, :autofocus => true, :class => "form-control" %>
				</div>

				<div class="input-div">
					<%= f.label :body %>
					<%= f.text_area :body, :class => "form-control" %>
				</div>

				<div class="input-div">
					<%= f.submit "Create", :class => "btn btn-default" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/topics/show.html.erb
<div class="container">
	<h1><%= @topic.title %></h1>
	<p><%= @topic.body %></p>
	<p><%= time_tag @topic.created_at.localtime %></p>

	<p><%= link_to "List", course_topics_path(@course) %> | <%= link_to "Edit", edit_course_topic_path(@course, @topic) %> | <%= link_to "Delete", course_topic_path(@course, @topic), method: :delete, data: { confirm: "Are you sure?" } %></p>
</div>
</div>