config/routes.rb
Whiteboard::Application.routes.draw do

	devise_for :students
	devise_for :teachers
	
	resources :students, only: [:show]

	resources :teachers, only: [:show]

	resources :courses do
		resources :assignments
		resources :grades
		resources :topics

		resources :events, except: [:index]
		get '/calendar' => 'events#index'

		resources :enrolls, only: [:create, :index, :destroy]
	end

	root to: 'pages#home'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController

	before_filter :find_course, except: [:new, :create, :index]

	def new
		@course = Course.new
	end

	def create
		@course = Course.new(course_params)

		if @course.save
			flash[:success] = "Course was created"
			redirect_to course_path(@course)
		else
			flash[:error] = "Error while creating course"
			render "new"
		end
	end

	def show
	end

	def edit
	end

	def update
		if @course.update_attributes(course_params)
			flash[:success] = "Course was updated"
			redirect_to course_path(@course)
		else
			flash[:error] = "Error while updating course"
			render "edit"
		end
	end

	def index
		@courses = Course.all
	end

	def destroy
		@course.destroy!

		flash[:info] = "Course was deleted"
		redirect_to courses_path
	end

	private
		def course_params
			params.require(:course).permit(:teacher_id, :department, :number, :section, :title, :term, :start_time, :end_time, :description)
		end

		def find_course
			@course = Course.find(params[:id])
		end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/edit.html.erb
<div class="container">
	<div class="panel panel-info">
		<div class="panel-heading">
			<strong>Edit Course</strong>
		</div>

		<div class="panel-body">
			<%= form_for @course do |f| %>
				<div>
					<%= f.label :title %>
					<%= f.text_field :title, :autofocus => true, :class => "form-control " %>
				</div>

				<div class="input-div">
					<%= f.label :department %>
					<%= f.text_field :department, :class => "form-control " %>
				</div>

				<div class="input-div">
					<%= f.label :number %>
					<%= f.text_field :number, :class => "form-control " %>
				</div>

				<div class="input-div">
					<%= f.label :section %>
					<%= f.text_field :section, :class => "form-control " %>
				</div>

				<div class="input-div">
					<%= f.label :term %>
					<%= f.text_field :term, :class => "form-control " %>
				</div>

				<div class="input-div">
					<%= f.label :start_time %>
					<%= f.text_field :start_time, :class => "form-control " %>
				</div>

				<div class="input-div">
					<%= f.label :end_time %>
					<%= f.text_field :end_time, :class => "form-control " %>
				</div>

				<div class="input-div">
					<%= f.label :description %>
					<%= f.text_area :description, :class => "form-control " %>
				</div>

				<div class="input-div">
					<%= f.submit "Edit", :class => "btn btn-default" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/courses/index.html.erb
<div class="container">
	<h1>Courses</h1>
	<table class="table table-striped table-hover">
		<thead>
			<td>Title</td>
			<td>Course ID</td>
		</thead>

		<tbody>
			<% @courses.each do |course| %>
				<tr>
					<td><%= link_to course.title, course_path(course) %></td>
					<td><%= course_id(course) %></td>
				</tr>
			<% end %>
		</tbody>
	</table>

	<p><%= link_to "New", new_course_path %></p>
</div>

app/views/courses/new.html.erb
<div class="container">
	<div class="panel panel-info">
		<div class="panel-heading">
			<strong>Create Course</strong>
		</div>

		<div class="panel-body">
			<%= form_for @course do |f| %>
				<div>
					<%= f.label :title %>
					<%= f.text_field :title, :autofocus => true, :class => "form-control " %>
				</div>

				<div class="input-div">
					<%= f.label :department %>
					<%= f.text_field :department, :class => "form-control " %>
				</div>

				<div class="input-div">
					<%= f.label :number %>
					<%= f.text_field :number, :class => "form-control " %>
				</div>

				<div class="input-div">
					<%= f.label :section %>
					<%= f.text_field :section, :class => "form-control " %>
				</div>

				<div class="input-div">
					<%= f.label :term %>
					<%= f.text_field :term, :class => "form-control " %>
				</div>

				<div class="input-div">
					<%= f.label :start_time %>
					<%= f.text_field :start_time, :class => "form-control " %>
				</div>

				<div class="input-div">
					<%= f.label :end_time %>
					<%= f.text_field :end_time, :class => "form-control " %>
				</div>

				<div class="input-div">
					<%= f.label :description %>
					<%= f.text_area :description, :class => "form-control " %>
				</div>

				<div class="input-div">
					<%= f.submit "Create", :class => "btn btn-default" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/courses/show.html.erb
<div class="container">
	<h1><%= "#{course_id(@course)} #{@course.title}" %></h1>
	<p><%= @course.teacher.name %></p>
	<p><%= "#{@course.term} #{@course.start_time} - #{@course.end_time}" %></p>
	<p><%= @course.description %></p>

	<p><%= link_to "Assignments", course_assignments_path(@course) %></p>
	<p><%= link_to "Calendar", course_calendar_path(@course, month: Date.today.month, year: Date.today.year) %></p>
	<p><%= link_to "Topics", course_topics_path(@course) %></p>

	<% if student_signed_in? && current_student.enrolled?(@course) %>

		<p><%= link_to "Drop Class", course_enroll_path(@course, Enroll.find_by(student_id: current_student.id, course_id: @course.id)), method: :delete, :class => "btn btn-danger" %></p>
	<% else %>

		<p><%= link_to "Enroll", course_enrolls_path(@course), method: :post, :class => "btn btn-primary" %></p>
	<% end %>

	<p><%= link_to "List", courses_path %> | <%= link_to "Edit", edit_course_path(@course) %> | <%= link_to "Delete", course_path(@course), method: :delete, data: { confirm: "Are you sure?" } %></p>
</div>